Document: wpilib-cpp-plugin-files
Title: Debian wpilib-cpp-plugin-files Manual
Author: <insert document author here>
Abstract: This manual describes what wpilib-cpp-plugin-files is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wpilib-cpp-plugin-files/wpilib-cpp-plugin-files.sgml.gz

Format: postscript
Files: /usr/share/doc/wpilib-cpp-plugin-files/wpilib-cpp-plugin-files.ps.gz

Format: text
Files: /usr/share/doc/wpilib-cpp-plugin-files/wpilib-cpp-plugin-files.text.gz

Format: HTML
Index: /usr/share/doc/wpilib-cpp-plugin-files/html/index.html
Files: /usr/share/doc/wpilib-cpp-plugin-files/html/*.html
